### PR TITLE
Feature/#49 crud operation for users

### PR DESCRIPTION
**Pull request by Kerosz**
This branch will address issue #49 .It will contain the full user CRUD operations plus User Schema and DTO's

Resolves #49

### CODE REVIEW

**Review by Kerosz — COMMENTED** [review]
@sohanur-rahman0 I need you to review [this commit](https://github.com/chingu-voyages/v33-bears-team-15be/pull/1/commits/e18325ab1a2d538d53ba05a11550c90cd14d7e10) for me. I want you to look at that **embeded** field in the UserEntity => `readingList`

I know you mentioned you want it as an embeded field and not a separate collection. The way I set up the type of it is an array of ObjectId type wich references `readingList` as a collection. I'm not exactly sure how to do it as an embeded field.

**Review by sohanur-rahman0 — COMMENTED** [review]
It looks ok.....

**Comment by Kerosz** [comment]
@sohanur-rahman0 Is this the way you do it though ? I know this is the way you do it when you have another collection. Do sub collections work the same way ?

**Comment by sohanur-rahman0** [comment]
No....you are referencing here.....It is similar to foreign key.......It's not embedding.....It would be embedding when you push  readingList documents inside user document....for example in a field like readingLists array....

**Pull request merged**
